config/routes.rb
DeviseApp::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  match ':controller(/:action(/:id(.:format)))'
  
  resources :authentications
  resources :pages
  devise_for :users, :controllers => {:registrations => 'registrations'} do
    resources :chat
    resources :messages
  end
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match "/chat/:id" => "chat#view"
  match "/new" => "chat#new"
  
  root :to => "pages#home"

  
  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :provider, :uid
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/chat_user.rb
class ChatUser < ActiveRecord::Base
  
  def self.user(session)
    
    if session[:user_id] == nil
      user = self.new
      user.nickname = "user_" + Time.now.to_i.to_s
      if user.save
        session[:user_id] = user.id
      end
    else
      user = self.find(session[:user_id])
    end

    # Return the user
    user
    
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :authentications
  has_many :messages, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  
  def apply_omniauth(omniauth)
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  
  def update_nickname
    if params[:user_id] != nil && params[:nickname] != nil
      user = ChatUser.find(params[:user_id])
      old_nickname = user.nickname
      user.nickname = params[:nickname]
      if user.save
        chat = Chat.find(params[:chat_id])
        payload = { :old_nickname => old_nickname, :nickname => user.nickname, :user_id => user.id }
        Pusher["presence-" + chat.channel].trigger('updated_nickname', payload)
        render :text => "SAVED"
      else
        render :text => "ERROR"
      end
    else
      render :text => "ERROR"
    end
  end

  def post_message
    chat = Chat.find(params[:chat_id])
    message = Message.new
    message.chat_id = chat.id
    
    user = ChatUser.user(session)
    message.user_id = user.id
    message.message = params[:message]
    
    payload = message.attributes
    payload[:user] = user.attributes
    
    if message.save
      Pusher["presence-" + chat.channel].trigger('send_message', payload)
      render :text => "sent"
    else
      render :text => "failed"
    end
  end

  def typing_status
    if params[:chat_id] != nil && params[:status] != nil
      chat = Chat.find(params[:chat_id])
      user = ChatUser.user(session)
      
      payload = { :user => user.attributes, :status => params[:status] }
      Pusher["presence-" + chat.channel].trigger('typing_status', payload)
    end
    render :text => ""
  end

  def authenticate
    if params[:user_id]
      user = ChatUser.find(params[:user_id])
      auth = Pusher[params[:channel_name]].authenticate(params[:socket_id],
        :user_id => user.id,
        :chat_user => user.attributes
      )
      render :json => auth
    else
      render :text => "Not authorized", :status => '403'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    messages_path(resource)
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end


  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully"
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully"
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end  
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  
  def new
    chat = Chat.find(params[:chat])
  end
  
  
  
  def new
        chat = Chat.new
        chat.owner = ChatUser.user(session)
        if chat.save
          chat_tiny = Tiny::tiny(chat.id)
            chat.channel = "message_channel_" + chat.id.to_s
            chat.save
          redirect_to :action => "view", :id => chat_tiny
         else
           redirect_to authentications_url
        end
      end

   def view

     if(params[:id] != nil)
       @chat = Chat.find(Tiny::untiny(params[:id]))
       @user = ChatUser.user(session)
       @messages = Message.find(:all, :conditions => ["chat_id = ?", @chat.id.to_s])
     else
       redirect_to :controller => 'message', :action => 'index'
     end

   end
   
   def index  
    @chat = Chat.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    if @authentications = current_user
      @messages = Message.all
    else
      redirect_to authentications_url
      flash[:notice] = "You need to sign in before answering questions"
    end
  end
  
  def create
    @user = User.find(params[:message][:user_id])
    @message = @user.messages.create!(params[:message])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @home = "Home"
  end
  
  def about
    @about = "About"
  end
  
  def contact
    @contact = "Contact"
  end
  
  # def messages
  #     # Get the chat user by passing in the current cookie session
  #     @user = ChatUser.user(session)
  #   end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://localhost:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authentications/index.html.erb
<div class="sign_in">
	<h1>Start Answering Questions Now!</h1>
	<% if @authentications %>
	  <% unless @authentications.empty? %>
	    <p><strong>You can sign in to this account using:</strong></p>
	    <div class="authentications">
	      <% for authentication in @authentications %>
	        <div class="authentication">
	          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
	          <div class="provider"><%= authentication.provider.titleize %></div>
	          <div class="uid"><%= authentication.uid %></div>
	          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
	        </div>
	      <% end %>
	    </div>
	  <% end %>
	  <p><strong>Add another service to sign in with:</strong></p>
	<% else %>
	  <p><strong>Simple Sign-in Through Twitter</strong></p>
	<% end %>

	<a href="/auth/twitter" class="auth_provider">
	  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
	  Twitter
	</a>
	<div id="other_signup">
		<% unless user_signed_in? %>
		  <p>
		    <strong>Don't use these services?</strong>
		    <%= link_to "Sign up", new_user_registration_path %> or
		    <%= link_to "Sign in", new_user_session_path %> with a password.
		  </p>
		<% end %>
	</div>
	<div class="account_info">
		<p>We will not share your info with anyone</p>
	</div>
</div>

app/views/chat/index.html.erb
<table>
	<%= @chats.each do |chat| %>
		<tr>
			<td><%= chat.owner %></td>
			<td><%= link_to chat.channel, chat %></td>
		</tr>
	<% end  %>
</table>

app/views/chat/view.html.erb
<script type="text/javascript">
	// Set the globals used by chat.js
	channel = "<%= @chat.channel %>";
	chat_id = "<%= @chat.id %>";
	user_id = "<%= @user.id %>";
</script>

<%= javascript_include_tag "http://js.pusherapp.com/1.7/pusher.min.js", "chat" %>

<div class="chat">
	<div id="wrapper">
		<div class="header">
			<div id="title" class="member_list_title">Quezzi (<span id="room_count">0</span>)</div>
			<a href="#" id="editNickname">Change Nickname</a>
				<input type="text" value="<%= @user.nickname %>" id="nickname" />
				<a href="#" id="saveNickname">Save</a>
			<a class="right tiptip" href="#" title="<b>How to Invite...</b><br />Simply share the URL of this page with anybody else to invite them to the chatter!">Invite</a>
			<span id="loading"></span>
		</div>
		<ul id="messages">
			<% @messages.each do |message| %>
				<% user = ChatUser.find(message.user_id) %>
				<li<% if user.id == @user.id %> class="you"<% end %>><strong><%= user.nickname %></strong> said:<br><%= auto_link_urls(message.message, { :target => "_blank" }) %></li>
			<% end %>
		</ul>
		<div id="message-overlay"></div>
		<textarea disabled="disabled" id="message" name="message">Type your message here and hit enter...</textarea>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About Us", about_path %></li>
			<li><%= link_to "Contact Us", contact_path %></li>				
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
		<a href="/" class="header_logo">
		  <%= image_tag "quezzi.png", :alt => "Quezzi Logo" %>
		</a>
	<div id="user_nav">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %><br /> 
      Not you?
      <%= link_to "Sign out", destroy_user_session_path %> 
    <% else %>
      <%= link_to "Sign In", authentications_path %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quezzi</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	<script type="text/javascript" charset="utf-8">
    var PUSHER_KEY = '<%= Pusher.key %>'
  </script>
  <%= javascript_include_tag "http://js.pusherapp.com/1.8/pusher.min.js", "jquery.tipTip.minified", "base", "chat.functions" %>
</head>
	
	<body>
		<div id="container">
			<%= render 'layouts/header'%>
			<%= yield %>
			<%= render 'layouts/footer'%>
		</div>
	</body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <%= message.user_id %>:<%= message.content %> 
</li>

app/views/messages/create.js.erb
<% broadcast "/messages" do %>
  $("#chat").append("<%= escape_javascript render(@message) %>");
<% end %>
$("#new_message")[0].reset();

app/views/messages/index.html.erb
 <div id="wrapper">
	
    <div class="header">
		<div id="title">Quezzi Chat</div>
		<div id="beta-bookmark" class="tiptip" title="<b>I'm in Beta!</b><br />Please email any bugs you find to tarnfeld[at]me.com! Happy chatting.">It's only a beta!</div>
    </div>

    <div class="inner">
		<p>A real-time chat web app powered by <a href="http://pusherapp.com/" target="_blank">Pusher</a>, built by <a href="http://tarnfeld.com/" target="_blank"></a><br />To join in on the current chat, click below.</p>

		<%= link_to({:controller => "chat", :action => "view", :id => "Q"}, {:class => "button"}) do %>
			<button>New Chat</button>
		<% end %>

	</div>

</div>

app/views/messages/index1.html.erb
<h2>Question</h2>

<h4>
	Which company makes the best Iphone 4 case?
</h4>


<ul id="chat">
  <%= render @messages %>
</ul>

<div class="message_form">
	<%= form_for current_user.messages.new, :remote => true do |f| %>
	<div class="field">
	  <%= f.text_field :content %>
	</div>
	<div class="field">
		<%= f.hidden_field :user_id %>
	</div>	
	<div class="actions">
		<%= f.submit "Send" %>
	</div>
	<% end %>
</div>

app/views/pages/about.html.erb
<h1>About.</h1>

<h3>What is Quezzi?</h3>

<p>Quezzi is a real time question and answer platform. Ask a question and get a response from the community with the opportunity for whatever followups you have.</p>

<h3>Why should I try another Q&A service?</h3>

<p>Although there are plenty of Q&A services on the web, none of them answer the questions to the degree that everyone wants. A question gets the "best answer" and then the thread just sits there to decay. Why should a question become static once it's answered? What about the follow up questions? In order to be useful, there needs to be a discussion with an evolution of questions and answers - this can be solved through a real time chat and it is exactly what Quezzi is trying to do.</p>

<h3>Why can't I create my own question?</h3>

<p>Right now, for the sake of testing, I want to see what kind of demand there is for real time chat around these questions. To do this I've decided that I am only going to host one question per week. If you would like to ask a question please contact me at quezzi[at]gmaildotcom and I will store for a future posting.</p>

<h3>Do you want feedback?</h3>

<p>Please and Always! I am looking for all the feedback I can get and how I can make this site more useful for everyone. I absolutely feel that real-time chat is key to a quality discussion and I am trying to see if that can be translated into a question and answer platform. </p>

app/views/pages/contact.html.erb
<h1>Let's Talk!</h1>

<h3>Please send me your feedback, future Quezzi questions and any comments that you may have to quezzi[at]gmail.com . I want to work with you to make this as helpful as it can be!</h3>

app/views/pages/home.html.erb
<div class="landing">
	<div class="center">
		<h2>Questions Asked and Answered, Quickly!</h2>
	</div>
	<div class="value">
		<table>
			<tr>
					<td>
						<img src="/images/speech_bubbles5.png"></img> 
					</td>
					<td>
						<p><strong>Don't trust Q&A sites?</strong>
							<br />Quezzi incorporates your friends to give you answers that you trust.</p>
					</td>
			</tr>
			<tr>
				<td>
					<img src="/images/speech_bubbles5.png"></img>
				</td>
				<td>
					<p><strong>Q&A shouldn't end with the answer!</strong> 
						<br />
						There needs to be a discussion and here you can do that.</p>
				</td>
			</tr>
			<tr>
				<td>
					<img src="/images/user_comment.png"></img>
				</td>
				<td>
					<p><strong>Instant Responses</strong><br />Some questions need instant responses and that is exactly what we support!</p>
				</td>
			</tr>
		</table>
	</div>

	<div class="sample_question">
		<h3>Current Question:</h3>
		<p>What Is A Good Father's Day Gift?</p>
	</div>
	<div class="signup_button">
		<% if user_signed_in? %>
			<a class="button" href="/messages"><span>Answer Questions!</span></a>
		<% else %>
			<a class="button" href="/authentications"><span>Answer Questions!</span></a>
		<% end %>
	</div>
</div>
	

	<!-- <%= link_to "Answer A Question", :controller => 'messages', :action => 'index' %> -->